SELECT
	OBJECT_NAME(F.OBJECT_ID) OBJ,
	I.NAME IND,
	F.partition_number,
	F.index_type_desc,
	F.alloc_unit_type_desc,
	F.AVG_FRAGMENTATION_IN_PERCENT,
	F.PAGE_COUNT,
	S.TABLE_SCHEMA,
	F.*
FROM
	SYS.DM_DB_INDEX_PHYSICAL_STATS (DB_ID(),NULL,NULL,NULL,'DETAILED') F
	JOIN
	SYS.INDEXES I
	ON
		(F.OBJECT_ID=I.OBJECT_ID)
		AND
		I.INDEX_ID=F.INDEX_ID
	JOIN	
	INFORMATION_SCHEMA.TABLES S
	ON
		(S.TABLE_NAME=OBJECT_NAME(F.OBJECT_ID))
		AND
		S.TABLE_SCHEMA = OBJECT_SCHEMA_NAME(F.OBJECT_ID)
WHERE
	I.INDEX_ID <> 0
	AND
	F.DATABASE_ID=DB_ID()
	AND
	OBJECTPROPERTY(I.OBJECT_ID,'ISSYSTEMTABLE')=0